version: "3.8"

services:
  platform:
    build: .
    image: platform-backend
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    env_file:
      - local.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - staticfiles:/app/staticfiles/
    depends_on:
      - postgres

  # worker:
  #   image: sarisuki-platform
  #   command: celery -A platform_backend.messagebus.celery worker --loglevel=INFO
  #   env_file:
  #     - local.env
  #   volumes:
  #     - ./:/app

  # scheduler:
  #   image: sarisuki-platform
  #   command: celery -A platform_backend.messagebus.celery beat --loglevel=INFO
  #   env_file:
  #     - local.env
  #   volumes:
  #     - ./:/app

  postgres:
    image: postgres:17
    environment:
      - local.env
    volumes:
      - pg-volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pg-volume:
  staticfiles:
    external: true