# Generated by Django 4.0.6 on 2022-08-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='special',
        ),
    ]
