# Generated by Django 4.0.6 on 2022-09-07 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_cartpromo_cart_deliveryaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpromoclaim',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='store.order'),
        ),
        migrations.AlterField(
            model_name='userpromoclaim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
