# Generated by Django 4.1 on 2022-08-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('name', 'address', 'province')},
        ),
    ]
