# Generated by Django 4.1 on 2022-08-15 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_alter_store_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Pickup')], db_index=True, max_length=50, null=True)),
                ('payment_method', models.CharField(choices=[('COD', 'cash on delivery'), ('CARD', 'Card')], db_index=True, default='COD', max_length=50)),
                ('payment_status', models.CharField(choices=[('TO_COLLECT', 'To collect'), ('UNPAID', 'Unpaid'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], db_index=True, default='TO_COLLECT', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FOR_APPROVAL', 'For approval'), ('FOR_PROCESSING', 'For processing'), ('PROCESSING', 'Processing'), ('FOR_DISPATCH', 'For Dispatch'), ('DISPATCHED', 'Dispatched'), ('ENROUTE', 'Enroute'), ('ARRIVED', 'Arrived'), ('RECEIVED', 'Received'), ('REPORTED', 'Reported'), ('PACKED', 'Packed'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('RETURNED', 'Returned')], db_index=True, default='PENDING', max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='store.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
