# Generated by Django 4.0.6 on 2022-08-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'cash on delivery'), ('CARD', 'Card')], db_index=True, default='TO_COLLECT', max_length=50),
        ),
    ]
