# Generated by Django 4.1 on 2022-08-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
    ]
