# Generated by Django 4.1 on 2022-08-22 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import platform_backend.store.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_default_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='items_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sellable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('upload', models.ImageField(upload_to=platform_backend.store.models.products.get_image_path)),
                ('default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='store.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
