# Generated by Django 4.0.6 on 2022-08-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
