# Generated by Django 4.1 on 2022-08-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_image_product_items_sold_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergories',
            new_name='Categories',
        ),
    ]
