# Generated by Django 4.1 on 2022-08-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_catergories_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'cash on delivery'), ('CARD', 'Card')], db_index=True, default='TO_COLLECT', max_length=50),
        ),
    ]
