# Generated by Django 4.0.6 on 2022-08-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_avg_rating'),
        ('store', '0007_alter_order_payment_method'),
    ]

    operations = [
    ]
