# Generated by Django 4.1 on 2022-08-23 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
        ('store', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='store.cart')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='promo.promo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
