# Generated by Django 4.1 on 2022-08-24 09:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_cartpromo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('owner', 'store')},
        ),
    ]
