# Generated by Django 4.1 on 2022-08-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cart_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default_price',
        ),
        migrations.AddField(
            model_name='product',
            name='floor_price',
            field=models.DecimalField(decimal_places=4, default=-1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
