# Generated by Django 4.1 on 2022-08-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_default_price_product_floor_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
