# Generated by Django 4.0.6 on 2022-08-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_merge_20220825_0825'),
        ('store', '0011_alter_cartitem_unique_together'),
    ]

    operations = [
    ]
