# Generated by Django 4.0.6 on 2022-08-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_avg_rating_productimage_avg_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
