# Generated by Django 4.0.6 on 2022-08-21 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rating_type', models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], max_length=50, null=True)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='store.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_type', models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('LOGISTIC', 'Logistic')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_tags', to='rating.rating')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_tags', to='rating.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='store.product')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='rating.rating')),
            ],
        ),
        migrations.CreateModel(
            name='AdminRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_ratings', to='rating.rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
