# Generated by Django 4.1 on 2022-08-26 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimport',
            name='import_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 2, 50, 25, 722155, tzinfo=datetime.timezone.utc)),
        ),
    ]
