# Generated by Django 4.1 on 2022-08-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productimport_import_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimport',
            name='import_date',
            field=models.DateField(),
        ),
    ]
