# Generated by Django 4.0.6 on 2022-08-25 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_user_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_due_date', models.DateField(blank=True, null=True)),
                ('total_order', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total_charges', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total_due', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DRAFT', 'Draft'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid')], default='DRAFT', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('payment_method', models.CharField(choices=[('COD', 'cash on delivery'), ('CARD', 'Card')], max_length=50)),
                ('invoice_url', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', max_length=16)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_payment', to='payment.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CODPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=254, null=True)),
                ('province', models.CharField(blank=True, max_length=254, null=True)),
                ('shipping_cost', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', max_length=16)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cod_payment', to='payment.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
