# Generated by Django 4.0.6 on 2022-08-25 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='card_brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='card_expired_at',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 9, 53, 39, 259171)),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='card_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='card_type',
            field=models.CharField(choices=[('VISA', 'visa'), ('MASTERCARD', 'mastercard'), ('AMERICAN EXPRESS', 'american express'), ('DISCOVER', 'discover')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='last_4_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
