# Generated by Django 4.0.6 on 2022-08-28 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_onlinepayment_card_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='card_expired_at',
            field=models.DateField(default=datetime.datetime(2022, 8, 28, 10, 17, 18, 434074, tzinfo=utc)),
        ),
    ]
