# Generated by Django 4.0.6 on 2022-08-29 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_onlinepayment_card_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='card_expired_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
