# Generated by Django 4.0.6 on 2022-09-07 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import platform_backend.common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_cartpromo_cart_deliveryaddress'),
        ('payment', '0004_alter_onlinepayment_card_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codpayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='onlinepayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='store.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=platform_backend.common.models.fields.PriceField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
