# Generated by Django 4.0.6 on 2022-09-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_codpayment_status_remove_onlinepayment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
